name: drupal-test
recipe: drupal8
config:
  webroot: .
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app
  phpunitcov:
    service: appserver
    env:
      XDEBUG_MODE: coverage
    cmd: ./vendor/bin/phpunit -c ./core
